import Header from '@/components/shared/Header';
import Sidebar from '@/components/shared/Sidebar';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import styles from './layout.module.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: 'favicon.ico',
  },
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles['main-container']}>
          <Sidebar />
          <div className={styles['secondary-container']}>
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
