import Header from '@/components/Shared/Header';
import Sidebar from '@/components/Shared/Sidebar';
import PlayerContextWrapper from '@/components/Shared/Wrappers/PlayerContext';
import { Inter } from 'next/font/google';
import '../styles/globals.scss';
import styles from './layout.module.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: 'favicon.ico',
  },
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PlayerContextWrapper>
          <div className={styles.MainContainer}>
            <Sidebar />
            <div className={styles.SecondaryContainer}>
              <Header />
              {children}
            </div>
          </div>
        </PlayerContextWrapper>
      </body>
    </html>
  );
}
